apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kaimen-backend.name" . }}-config
  labels:
    {{- include "kaimen-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
