apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kaimen-backend.fullname" . }}
  labels:
    {{- include "kaimen-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kaimen-backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kaimen-backend.name" . }}
    spec:
      serviceAccountName: {{ include "kaimen-backend.fullname" . }}-sa
      containers:
        - name: {{ include "kaimen-backend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "kaimen-backend.fullname" . }}-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: {{ include "kaimen-backend.fullname" . }}-config
