apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaimen-backend.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaimen-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "kaimen-backend.name" . }}
