version: '3.8'

services:
  app:
    build: .
    container_name: kaimen-admin-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
    networks:
      - kaimen-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  kaimen-network:
    driver: bridge

volumes:
  logs: