# 简化版 FastAPI 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: jianbao-backend-config
  namespace: jianbao-system
  labels:
    app: jianbao-backend
data:
  # 应用基础配置
  app.yaml: |
    app:
      name: "jianbao-backend"
      version: "1.0.0"
      debug: false
      
    server:
      host: "0.0.0.0"
      port: 8000
      
    logging:
      level: "INFO"
      
      
    # CORS配置
    cors:
      allow_origins:
        - "https://admin.kaimen.site"
        - "https://*.jianbao.com"
      allow_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allow_headers:
        - "*"
      allow_credentials: true