# Python FastAPI 后端服务部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jianbao-backend
  namespace: jianbao-system
  labels:
    app: jianbao-backend
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jianbao-backend
  template:
    metadata:
      labels:
        app: jianbao-backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: jianbao-backend
      containers:
      - name: backend
        image: ccr.ccs.tencentyun.com/jianbao/backend:latest
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: WORKERS
          value: "4"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: redis-url
        - name: COS_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: cos-secret-id
        - name: COS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: cos-secret-key
        - name: COS_BUCKET
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: cos-bucket
        - name: COS_REGION
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: cos-region
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: jwt-secret
        - name: WECHAT_APP_ID
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: wechat-app-id
        - name: WECHAT_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: jianbao-secrets
              key: wechat-app-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: temp-storage
          mountPath: /tmp/processing
        - name: config
          mountPath: /app/config
          readOnly: true
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-logs
        emptyDir:
          sizeLimit: 1Gi
      - name: temp-storage
        emptyDir:
          sizeLimit: 2Gi
      - name: config
        configMap:
          name: jianbao-backend-config
      imagePullSecrets:
      - name: tcr-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30