# Kubernetes Secrets 配置
# 注意: 这个文件包含敏感信息的模板，实际部署时需要替换为真实值

# 鉴宝后端应用密钥
apiVersion: v1
kind: Secret
metadata:
  name: jianbao-secrets
  namespace: jianbao-system
  labels:
    app: jianbao-backend
type: Opaque
data:
  # 注意: 以下是base64编码的示例值，部署时需要替换为实际值
  # 使用命令生成: echo -n "your-actual-value" | base64
  
  # 数据库连接URL
  database-url: bXlzcWw6Ly91c2VyOnBhc3N3b3JkQGhvc3Q6MzMwNi9kYm5hbWU=  # mysql://user:password@host:3306/dbname
  
  # Redis连接URL
  redis-url: cmVkaXM6Ly9ob3N0OjYzNzkvMA==  # redis://host:6379/0
  
  # 腾讯云COS配置
  cos-secret-id: QUtJRHh4eHh4eHh4eHh4eHh4eHh4eA==  # AKIDxxxxxxxxxxxxxxxx
  cos-secret-key: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eA==  # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  cos-bucket: amlhbmJhby1idWNrZXQ=  # jianbao-bucket
  cos-region: YXAtZ3Vhbmd6aG91  # ap-guangzhou
  
  # JWT密钥
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLWppYW5iYW8=  # super-secret-jwt-key-for-jianbao
  
  # 微信小程序配置
  wechat-app-id: d3hYWFhYWFhYWFhYWFhYWA==  # wxXXXXXXXXXXXXXXXX
  wechat-app-secret: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eA==  # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  
---
# 腾讯云容器镜像仓库拉取密钥
apiVersion: v1
kind: Secret
metadata:
  name: tcr-secret
  namespace: jianbao-system
type: kubernetes.io/dockerconfigjson
data:
  # 腾讯云TCR登录配置
  # 生成命令: kubectl create secret docker-registry tcr-secret \
  #   --docker-server=ccr.ccs.tencentyun.com \
  #   --docker-username=<your-tcr-username> \
  #   --docker-password=<your-tcr-password> \
  #   --dry-run=client -o yaml
  .dockerconfigjson: eyJhdXRocyI6eyJjY3IuY2NzLnRlbmNlbnR5dW4uY29tIjp7InVzZXJuYW1lIjoidGNyX3VzZXJuYW1lIiwicGFzc3dvcmQiOiJ0Y3JfcGFzc3dvcmQiLCJhdXRoIjoiZEdOeVgzVnpaWEp1WVcxbE9uUmpjbDl3WVhOemQyOXlaQT09In19fQ==
  
---
# ArgoCD访问GitHub的SSH密钥（如果使用SSH）
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  # SSH私钥 (base64编码)
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K  # -----BEGIN OPENSSH PRIVATE KEY-----...
  
---
# ArgoCD GitHub令牌（如果使用HTTPS）
apiVersion: v1
kind: Secret
metadata:
  name: github-token-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/DynastySeek/kaimen-backend.git
  username: not-used
  password: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  # GitHub Personal Access Token
  
---
# ArgoCD管理员密码
apiVersion: v1
kind: Secret
metadata:
  name: argocd-initial-admin-secret
  namespace: argocd
type: Opaque
data:
  # 初始管理员密码 (base64编码)
  # 默认用户名: admin
  # 生成方法: htpasswd -bnBC 10 "" your-password | tr -d ':\n' | base64
  password: JDJhJDEwJGVOZmZzNWJXVzE3WmdkRXpHTE5kZU9wWURGaUhiL1ZPWmNHVEdYS0FUUWZiSUhkb3h3Nm1X  # admin123
  
---
# TLS证书（HTTPS访问）
apiVersion: v1
kind: Secret
metadata:
  name: argocd-tls
  namespace: argocd
type: kubernetes.io/tls
data:
  # TLS证书和私钥 (base64编码)
  # 可以使用Let's Encrypt或购买的SSL证书
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # -----BEGIN CERTIFICATE-----...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # -----BEGIN PRIVATE KEY-----...
  
---
# ServiceAccount令牌
apiVersion: v1
kind: Secret
metadata:
  name: jianbao-backend-token
  namespace: jianbao-system
  annotations:
    kubernetes.io/service-account.name: jianbao-backend
type: kubernetes.io/service-account-token