# Python FastAPI 后端服务暴露配置
apiVersion: v1
kind: Service
metadata:
  name: jianbao-backend-service
  namespace: jianbao-system
  labels:
    app: jianbao-backend
  annotations:
    service.beta.kubernetes.io/tencent-cloud-load-balancer-health-check-flag: "on"
    service.beta.kubernetes.io/tencent-cloud-load-balancer-health-check-path: "/health"
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: jianbao-backend
  sessionAffinity: None
---
# 用于内部服务发现的Headless Service
apiVersion: v1
kind: Service
metadata:
  name: jianbao-backend-headless
  namespace: jianbao-system
  labels:
    app: jianbao-backend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: jianbao-backend