name: Build and Deploy

on:
  push:
    branches: [ main, develop ]

env:
  REGISTRY: kaimen-hk.tencentcloudcr.com
  IMAGE_NAME: management.platform.backend/kaimen-admin-backend

jobs:
  build-and-push:
    # 所有分支都构建
    runs-on: ["self-hosted", "HK"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # 自动检出当前分支（main 或 develop）

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Tencent Cloud TCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/develop' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract primary image tag
        # docker/metadata-action 输出多个 tag，取第一个（带分支前缀的 SHA）
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | tail -n1)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "Built and pushed image: $TAG"

      - name: Save image tag to file
        run: |
          echo "${{ env.IMAGE_TAG }}" | sed 's/.*://' > .image-tag
          ls -la .image-tag
      
      - name: Upload image tag as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag-${{ github.ref_name }}
          path: .image-tag
          if-no-files-found: error

  deploy-to-dev:
    name: Deploy to Dev Environment
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: build-and-push
    runs-on: ["self-hosted", "HK"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag-${{ github.ref_name }}  # 会自动变成 image-tag-develop 或 image-tag-main
          path: .
      
      - name: Read image tag
        run: |
          TAG=$(cat .image-tag)
          echo "Deploying image: $TAG"
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Configure KUBECONFIG from secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          yq e '(.contexts[].context.user) |= tostring | (.users[].name) |= tostring' -i /tmp/kubeconfig
          mkdir -p $HOME/.kube
          mv /tmp/kubeconfig $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify kubectl connection
        run: kubectl cluster-info

      - name: Deploy with Helm
        run: |
          helm upgrade --install kaimen-admin-backend-dev ./charts/kaimen-backend \
            --namespace kaimen-admin-dev --create-namespace \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set-string secrets.MYSQL_USER=${{ secrets.MYSQL_USER }} \
            --set-string secrets.MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            --set-string secrets.MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            --set secrets.MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
            --set-string secrets.MYSQL_DB=${{ secrets.MYSQL_DB }} \
            --set-string imagePullSecrets.username=${{ secrets.TCR_USERNAME }} \
            --set-string imagePullSecrets.password=${{ secrets.TCR_PASSWORD }} \
            --set config.SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --set-string config.ENVIRONMENT=development

  deploy-to-prod:
    name: Deploy to Prod Environment
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build-and-push
    runs-on: ["self-hosted", "HK"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag-main
          path: .

      - name: Read image tag
        id: get_tag
        run: |
          TAG=$(cat .image-tag)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "Using image: $TAG"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Configure KUBECONFIG from secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          yq e '(.contexts[].context.user) |= tostring | (.users[].name) |= tostring' -i /tmp/kubeconfig
          mkdir -p $HOME/.kube
          mv /tmp/kubeconfig $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify kubectl connection
        run: kubectl cluster-info

      - name: Deploy with Helm (dynamic image tag)
        run: |
          helm upgrade --install kaimen-admin-backend ./charts/kaimen-backend \
            --namespace kaimen-admin --create-namespace \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set-string secrets.MYSQL_USER='${{ secrets.MYSQL_USER }}' \
            --set-string secrets.MYSQL_PASSWORD='${{ secrets.MYSQL_PASSWORD }}' \
            --set-string secrets.MYSQL_HOST='${{ secrets.MYSQL_HOST }}' \
            --set secrets.MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
            --set-string secrets.MYSQL_DB='${{ secrets.MYSQL_DB }}' \
            --set-string imagePullSecrets.username=${{ secrets.TCR_USERNAME }} \
            --set-string imagePullSecrets.password=${{ secrets.TCR_PASSWORD }} \
            --set config.SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --set-string config.ENVIRONMENT=production
