name: Build and Deploy

on:
  push:
    branches: [ main, develop ]

env:
  REGISTRY: kaimen-hk.tencentcloudcr.com
  IMAGE_NAME: management.platform.backend/kaimen-admin-backend

jobs:
  build-and-push:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ["self-hosted", "HK"]
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Tencent Cloud TCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set IMAGE_TAG environment variable
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | tail -n1)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Update Helm values.yaml with commit tag
        run: |
          echo "Updating charts/kaimen-backend/values.yaml with image tag $IMAGE_TAG"
          yq e ".image.tag = \"${IMAGE_TAG##*:}\"" -i charts/kaimen-backend/values.yaml

      - name: Create Pull Request to update image tag
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update kaimen-backend image tag to ${{ env.IMAGE_TAG }} [skip ci]"
          branch: ci/update-image-tag-${{ github.run_number }}
          title: "chore: Auto-update kaimen-backend image tag"
          body: |
            This PR updates the Helm chart image tag to the latest build.
            - Image: `${{ env.IMAGE_TAG }}`
            - CI run: #${{ github.run_number }}
            - [skip ci]
          base: develop
          labels: automated, skip-ci
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      
      - name: Auto-merge the PR (if created)
        if: steps.cpr.outputs.pull-request-operation == 'created' || steps.cpr.outputs.pull-request-operation == 'updated'
        env:
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Enable auto-merge via GitHub CLI
          gh pr merge --auto --merge "$PR_URL"
      


  deploy-to-develop:
    name: Deploy to Dev Environment
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: build-and-push
    runs-on: ["self-hosted", "HK"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine image tag from current commit
        run: |
          # 镜像 tag 就是当前 commit SHA（与 develop 构建时一致）
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Configure KUBECONFIG from secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          yq e '(.contexts[].context.user) |= tostring | (.users[].name) |= tostring' -i /tmp/kubeconfig
          mkdir -p $HOME/.kube
          mv /tmp/kubeconfig $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify kubectl connection
        run: kubectl cluster-info

      - name: Deploy with Helm
        run: |
          helm upgrade --install kaimen-admin-backend-dev ./charts/kaimen-backend \
            --namespace kaimen-admin-dev --create-namespace \
            --set secrets.MYSQL_USER=${{ secrets.MYSQL_USER }} \
            --set secrets.MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            --set secrets.MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            --set secrets.MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
            --set secrets.MYSQL_DB=${{ secrets.MYSQL_DB }} \
            --set-string imagePullSecrets.username=${{ secrets.TCR_USERNAME }} \
            --set-string imagePullSecrets.password=${{ secrets.TCR_PASSWORD }} \
            --set config.SECRET_KEY=${{ secrets.SECRET_KEY }}
            
  deploy-to-prod:
    name: Deploy to Prod Environment
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ["self-hosted", "HK"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine image tag from current commit
        run: |
          # 镜像 tag 就是当前 commit SHA（与 main 构建时一致）
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Configure KUBECONFIG from secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          yq e '(.contexts[].context.user) |= tostring | (.users[].name) |= tostring' -i /tmp/kubeconfig
          mkdir -p $HOME/.kube
          mv /tmp/kubeconfig $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify kubectl connection
        run: kubectl cluster-info

      - name: Deploy with Helm
        run: |
          # 注意：这里直接使用 commit SHA 作为 tag（与构建时一致）
          helm upgrade --install kaimen-admin-backend ./charts/kaimen-backend \
            --namespace kaimen-admin --create-namespace \
            --set secrets.MYSQL_USER=${{ secrets.MYSQL_USER }} \
            --set secrets.MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            --set secrets.MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            --set secrets.MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
            --set secrets.MYSQL_DB=${{ secrets.MYSQL_DB }} \
            --set-string imagePullSecrets.username=${{ secrets.TCR_USERNAME }} \
            --set-string imagePullSecrets.password=${{ secrets.TCR_PASSWORD }} \
            --set config.SECRET_KEY=${{ secrets.SECRET_KEY }}
