name: Build and Push Docker Image to TCR

on:
  push:
    branches: [ main ]

env:
  REGISTRY: kaimen.tencentcloudcr.com
  IMAGE_NAME: management.platform.backend/kaimen-admin-backend

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Tencent Cloud TCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}  
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set IMAGE_TAG environment variable
        run: |
          # 取 metadata action 输出的最后一行 commit tag
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | tail -n1)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Update Helm values.yaml with commit tag
        run: |
          echo "Updating charts/kaimen-backend/values.yaml with image tag $IMAGE_TAG"
          yq e ".image.tag = \"${IMAGE_TAG##*:}\"" -i charts/kaimen-backend/values.yaml

      - name: Commit updated values.yaml (skip CI)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/kaimen-backend/values.yaml
          git commit -m "Update kaimen-backend image tag to ${IMAGE_TAG##*:} [skip ci]" || echo "No changes to commit"
          git push origin main
